### ISSUE TITLE
Can't extract or convert the album .igz file od skylanders imaginators

### ISSUE THREAD

**Issue by Peppins32** [AdventureT/IgzModelConverter#2]
As title say i'm unable to do anything with this files :/

ps4: [IMAGINATORS_0_ALBM_00.zip](https://github.com/AdventureT/IgzModelConverter/files/7699780/IMAGINATORS_0_ALBM_00.zip)
wii-u: [IMAGINATORS_0_ALBM_00.zip](https://github.com/AdventureT/IgzModelConverter/files/7699807/IMAGINATORS_0_ALBM_00.zip)

**Comment by AdventureT** [comment]
I know it's a bit late, but IgzModelConverter only extracts:
Crash Team Racing Nitro Fueled (Switch)
Crash Bandicoot: Nsane Trilogy (PC)
Skylanders Imaginators (Switch)
